; SPRITES.Z80
;
; Tile Source File.
;
; Info:
;   Section              : Sprites
;   Bank                 : 0
;   Form                 : All tiles as one unit.
;   Format               : Gameboy 4 color.
;   Compression          : None.
;   Counter              : None.
;   Tile size            : 16 x 16
;   Tiles                : 0 to 0
;
;   Palette colors       : None.
;   SGB Palette          : None.
;   CGB Palette          : None.
;
;   Convert to metatiles : No.
;
; This file was generated by GBTD v2.2

; Start of tile array.
DB $07,$07,$1F,$1F,$07,$05,$07,$05
DB $07,$05,$1F,$1F,$1E,$17,$1C,$1F
DB $09,$0F,$0E,$0E,$1C,$14,$5E,$5E
DB $3F,$3F,$10,$08,$10,$08,$00,$00
DB $E0,$E0,$E0,$E0,$E0,$60,$E0,$60
DB $E0,$A0,$F0,$F0,$F0,$D0,$70,$F0
DB $20,$E0,$E0,$E0,$E0,$A0,$F2,$F2
DB $FC,$FC,$10,$08,$10,$08,$00,$00

